-- Add migration script here

CREATE TABLE feed (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    title VARCHAR,
    updated DATETIME,
    description TEXT,
    language VARCHAR,
    published DATETIME
);

CREATE TABLE entry (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    feed_id INTEGER UNSIGNED NOT NULL,
    title VARCHAR,
    updated DATETIME,
    content_id INTEGER,
    summary TEXT,
    source VARCHAR,
    read BOOLEAN DEFAULT FALSE,
    media_id INTEGER,
    FOREIGN KEY(feed_id) REFERENCES feed(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(content_id) REFERENCES content(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(media_id) REFERENCES media(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE author (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR NOT NULL,
    uri VARCHAR,
    email VARCHAR
);

CREATE TABLE link (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    href VARCHAR NOT NULL,
    rel VARCHAR,
    media_type VARCHAR,
    href_lang VARCHAR,
    title VARCHAR,
    length BIGINT
);

CREATE TABLE content (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    body TEXT,
    content_type VARCHAR,
    length BIGINT,
    src INTEGER,
    FOREIGN KEY(src) REFERENCES link(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE category (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    term VARCHAR NOT NULL,
    scheme VARCHAR,
    label VARCHAR
);

CREATE TABLE IF NOT EXISTS media (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    title VARCHAR,
    thumbnail VARCHAR,
    description VARCHAR
);

CREATE TABLE feed_author (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    author_id INTEGER NOT NULL,
    feed_id INTEGER NOT NULL,
    FOREIGN KEY(author_id) REFERENCES author(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(feed_id) REFERENCES feed(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE entry_author (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    author_id INTEGER NOT NULL,
    entry_id INTEGER NOT NULL,
    FOREIGN KEY(author_id) REFERENCES author(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(entry_id) REFERENCES entry(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE feed_link (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    link_id INTEGER NOT NULL,
    feed_id INTEGER NOT NULL,
    FOREIGN KEY(link_id) REFERENCES link(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(feed_id) REFERENCES feed(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE entry_link (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    link_id INTEGER NOT NULL,
    entry_id INTEGER NOT NULL,
    FOREIGN KEY(link_id) REFERENCES link(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(entry_id) REFERENCES entry(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE media_link (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    link_id INTEGER NOT NULL,
    media_id INTEGER NOT NULL,
    FOREIGN KEY(link_id) REFERENCES link(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(media_id) REFERENCES media(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE feed_category (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    category_id INTEGER NOT NULL,
    feed_id INTEGER NOT NULL,
    FOREIGN KEY(category_id) REFERENCES category(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(feed_id) REFERENCES feed(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE entry_category (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    category_id INTEGER NOT NULL,
    entry_id INTEGER NOT NULL,
    FOREIGN KEY(category_id) REFERENCES category(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY(entry_id) REFERENCES entry(id) DEFERRABLE INITIALLY DEFERRED
);
